# 工具函数模块

from .logger import Logger, setup_logger, get_default_logger, logger
from .file_utils import (
    ensure_dir,
    ensure_parent_dir,
    safe_remove_file,
    safe_remove_dir,
    copy_file,
    move_file,
    get_file_size,
    format_file_size,
    list_files,
    get_unique_filename,
    clean_temp_files,
    validate_path,
)
from .audio_utils import (
    FFmpegError,
    AudioConversionError,
    detect_ffmpeg,
    get_ffmpeg_version,
    validate_ffmpeg,
    get_ffmpeg_path,
    check_ffmpeg_features,
    detect_audio_format,
    is_supported_audio_format,
    is_audio_file,
    get_audio_info,
    convert_audio_file,
    convert_to_opus,
    batch_convert_audio,
    AudioConversionParams,
    ConversionProgressMonitor,
    default_progress_callback,
    analyze_conversion_error,
    create_recovery_suggestion,
)

__all__ = [
    # 日志相关
    "Logger",
    "setup_logger",
    "get_default_logger",
    "logger",
    # 文件操作相关
    "ensure_dir",
    "ensure_parent_dir",
    "safe_remove_file",
    "safe_remove_dir",
    "copy_file",
    "move_file",
    "get_file_size",
    "format_file_size",
    "list_files",
    "get_unique_filename",
    "clean_temp_files",
    "validate_path",
    # 音频工具相关
    "FFmpegError",
    "AudioConversionError",
    "detect_ffmpeg",
    "get_ffmpeg_version",
    "validate_ffmpeg",
    "get_ffmpeg_path",
    "check_ffmpeg_features",
    "detect_audio_format",
    "is_supported_audio_format",
    "is_audio_file",
    "get_audio_info",
    "convert_audio_file",
    "convert_to_opus",
    "batch_convert_audio",
    "AudioConversionParams",
    "ConversionProgressMonitor",
    "default_progress_callback",
    "analyze_conversion_error",
    "create_recovery_suggestion",
]